Http Request Error Mailer
umts/microservices-router pull request #14
Opened 2016-10-20 16:17 UTC by mboneil10

I need to figure out how to use CONFIG in app/mailers/notifier_mailer.rb

2016-10-24 14:22 UTC, dfaulken commented on app/mailers/notifier_mailer.rb
> +    CONFIG.fetch(:notification_email)
Looks like you just called this but didn't use its value

2016-10-24 14:22 UTC, dfaulken commented on app/mailers/notifier_mailer.rb
> +class NotifierMailer < ApplicationMailer
Seems like we could just write

```ruby
class NotifierMailer < ActionMailer::Base
```

2016-10-24 14:23 UTC, dfaulken commented on config/environment.rb
> +CONFIG = YAML.load_file('config/application.yml')
Could also do

```ruby
YAML.load_file(whatever).symbolize_keys
```

2016-10-24 14:23 UTC, dfaulken commented on coverage/.last_run.json
> +    "covered_percent": 85.11
Why's this?

2016-10-24 14:24 UTC, dfaulken commented on lib/microservices_router.rb
> +      service_change_error(status)
Not sure if GitHub's showing the indentation weirdly, but these two lines should be indented inside the `else` block.

2016-10-24 14:24 UTC, dfaulken commented on spec/mailers/previews/notifier_preview.rb
> +class NotifierPreview < ActionMailer::Preview
Is this needed?

2016-10-24 15:20 UTC, mboneil10 commented on spec/mailers/previews/notifier_preview.rb
> +class NotifierPreview < ActionMailer::Preview
No

2016-10-24 15:20 UTC, mboneil10 commented on coverage/.last_run.json
> +    "covered_percent": 85.11
Added files that aren't tested?

2016-10-24 15:22 UTC, mboneil10 commented on lib/microservices_router.rb
> +      service_change_error(status)
Oops. I made this weird indentation.

2016-10-24 17:36 UTC, dfaulken requested changes

2016-10-24 17:36 UTC, dfaulken commented on app/mailers/notifier_mailer.rb
> +    mail to: notification_email,
Sure, may as well just write it inline without setting a local variable.

2016-10-24 17:36 UTC, dfaulken commented on config/application.yml
> +notification_email: 'transit-it@admin.umass.edu'
Are the quotes needed in YML?

2016-10-24 17:36 UTC, dfaulken commented on lib/microservices_router.rb
> +        service_change_error(status)
It's not clear in context from the method name that this is sending a notification.

2016-10-24 20:16 UTC, enragednuke commented on config/application.yml
> +notification_email: 'transit-it@admin.umass.edu'
They're used in round-three and jobapps, so that would lead me to assume so.

2016-10-24 20:18 UTC, dfaulken commented on config/application.yml
> +notification_email: 'transit-it@admin.umass.edu'
OK, but why assume? 😄 

From [wiki](https://en.wikipedia.org/wiki/YAML):

> Strings (scalars) are ordinarily unquoted, but may be enclosed in double-quotes ("), or single-quotes (').

Let's remove the quotes.

2016-10-24 20:21 UTC, ennukee commented on config/application.yml
> +notification_email: 'transit-it@admin.umass.edu'
:thinking: refactor round-three and jobapps YML or riot :thinking:

2016-10-24 20:21 UTC, enragednuke commented on config/application.yml
> +notification_email: 'transit-it@admin.umass.edu'
on that note, `.travis.yml` files don't use quotes for string elements.

2016-10-25 13:55 UTC, mboneil10 commented on app/mailers/notifier_mailer.rb
> +    mail to: notification_email,
Oh, right.

2016-10-25 13:58 UTC, mboneil10 commented on config/application.yml
> +notification_email: 'transit-it@admin.umass.edu'
Not sure why I added the quotes to begin with...

2016-10-25 14:36 UTC, mboneil10 commented on coverage/.last_run.json
> +    "covered_percent": 84.44
I can't figure this out. Please help @dfaulken

2016-10-25 14:49 UTC, mboneil10 commented on coverage/.last_run.json
> +    "covered_percent": 84.44
My guess is that the files I recently deleted (mailer preview and application mailer) had a part in the coverage.

2016-11-03 15:39 UTC, dfaulken approved these changes

2016-11-03 15:39 UTC, merged