Change changes made
umts/microservices-router pull request #29
Opened 2017-01-30 19:28 UTC by mboneil10

Referenced in #17

2017-01-30 19:57 UTC, dfaulken requested changes
Code looks great — could you push a documentation update also?

This is good to merge then.

2017-01-30 20:07 UTC, dfaulken commented
This closes #17.

2017-01-30 20:11 UTC, mboneil10 commented on coverage/.last_run.json
> +    "covered_percent": 72.55
@dfaulken forgot rspec. Hold on.

2017-01-31 18:29 UTC, dfaulken approved these changes

2017-02-01 15:41 UTC, merged