Don't Notify Service That Caused Changes
umts/microservices-router pull request #30
Opened 2017-02-06 16:33 UTC by akaplo

Closes #16.  Also adds tests for the ServiceChangeNotifier.

2017-02-07 18:07 UTC, akaplo commented
@dfaulken or @mboneil10, can one of you review?

2017-02-07 18:08 UTC, dfaulken commented
Sure. (Feel free to request reviews from us.)

2017-02-07 18:13 UTC, dfaulken requested changes
I made a stylistic pass. I'll let @mboneil10 read through for code functionality.

2017-02-07 18:13 UTC, dfaulken commented on app/controllers/services_controller.rb
> +    changed_service = nil
This shouldn't be necessary. If `changes_made` is false anyway, this variable doesn't need to be defined.

2017-02-07 18:13 UTC, dfaulken commented on app/controllers/services_controller.rb
> +          changed_service = service.id
Better to pass complete objects than just their IDs.

2017-02-07 18:13 UTC, dfaulken commented on app/lib/service_change_notifier.rb
> +  def notify_services_of_changes (initiating_service)
No space between method name and argument opening parenthesis.

2017-02-07 18:13 UTC, dfaulken commented on app/lib/service_change_notifier.rb
> +      next if (s.id == initiating_service.id)
Don't need parentheses around conditions.

2017-02-07 18:13 UTC, dfaulken commented on spec/mailers/notifier_spec.rb
> +    before(:each) do
Since we figured out what was going on with `use_transactional_fixtures`, it'd be good to convert this back to `let` blocks.

2017-02-07 18:13 UTC, dfaulken commented on spec/mailers/notifier_spec.rb
> +        .and_return Net::HTTPResponse.new('1.0', '200', '')
It'd be nice to document or comment what these arguments to `Net::HTTPResponse.new` are.

2017-02-07 18:13 UTC, dfaulken commented on spec/mailers/notifier_spec.rb
> +        notify_services_of_changes(@service_2)
Whoops, this shouldn't be indented.

2017-02-07 18:16 UTC, akaplo commented on app/controllers/services_controller.rb
> +    changed_service = nil
The JS developer in me says "but if we don't define it out here, how will we access it later?"

2017-02-07 18:18 UTC, dfaulken commented on app/controllers/services_controller.rb
> +    changed_service = nil
Yeah, Ruby's weird like that.

```ruby
if false
  a = nil
end
a # doesn't raise NameError, returns nil
```

2017-02-07 18:30 UTC, akaplo commented on app/controllers/services_controller.rb
> +    changed_service = nil
Removing that causes failures when `changes_made` is true as well - we can't access a variable that doesn't exist in the current scope, so don't we still need to define it here?

2017-02-07 18:32 UTC, dfaulken commented on app/controllers/services_controller.rb
> +    changed_service = nil
You shouldn't need to:

```ruby
if true
  a = 3
end
a # => 3
```

2017-02-07 20:01 UTC, dfaulken requested changes
Another small one.

2017-02-07 20:01 UTC, dfaulken commented on app/lib/service_change_notifier.rb
> +      next if s.id == initiating_service.id
Here too, you can compare objects rather than their IDs.

2017-02-07 20:32 UTC, dfaulken approved these changes

2017-02-23 17:55 UTC, akaplo commented
@mboneil10, lemme know your thoughts.

2017-02-23 18:49 UTC, mboneil10 approved these changes

2017-02-23 18:49 UTC, mboneil10 commented on app/controllers/services_controller.rb
> +    notify_services_of_changes(changed_service) if changes_made
Why was this moved?

2017-02-23 18:49 UTC, mboneil10 commented on app/lib/service_change_notifier.rb
> +      next if (s.id == initiating_service.id)
Will s ever be nil?

2017-02-23 18:49 UTC, mboneil10 commented on app/lib/service_change_notifier.rb
> +      if !response.is_a? Net::HTTPSuccess
Maybe use `unless` instead of `if !`

2017-02-24 16:05 UTC, akaplo commented on app/controllers/services_controller.rb
> +    notify_services_of_changes(changed_service) if changes_made
I don't remember now, but possibly it wasn't getting called.

2017-02-24 16:08 UTC, akaplo commented
@mboneil10 your comments were not on the current state of the PR - would you still like me to respond to each?

2017-02-24 16:10 UTC, akaplo commented
Also @dfaulken and @Anbranin, I'm not sure why CC is failing.  If you go to the details for the failure, it just says "no analysis present."  Did something change with our configuration?

2017-02-24 17:31 UTC, Anbranin commented
Okay @akaplo, I fixed the codeclimate check issue. It was because your branch was "out of date" with the default (master) branch. If you'd merged master into your branch before pushing I don't think it would have happened. There was a button and I pushed it, anyways, and I forgot what it said but it worked. So go ahead and fix those codeclimate issues. :)

2017-02-24 18:54 UTC, Anbranin commented on app/lib/service_change_notifier.rb
> -      next if s.url.nil?
Wait why are we not handling the nil thing any more?

2017-02-24 21:27 UTC, akaplo commented on app/lib/service_change_notifier.rb
> -      next if s.url.nil?
[Because](https://github.com/umts/microservices-router/blob/master/app/models/service.rb#L3).

2017-02-24 21:50 UTC, Anbranin commented on app/lib/service_change_notifier.rb
> -      next if s.url.nil?
Ooh right, there won't be one without a url. Makes sense. K

2017-02-24 21:57 UTC, dfaulken commented on app/lib/service_change_notifier.rb
>      Service.all.each do |s|
Code style nitpick, but perhaps `s` could be `service`?

2017-02-27 14:02 UTC, mboneil10 commented
@akaplo no need to respond to each. I've looked at files changed.

2017-02-27 18:42 UTC, Anbranin approved these changes

2017-02-28 17:51 UTC, merged